export const cityToEnglish: Record<string, string> = {
  "تهران": "Tehran",
  "مشهد": "Mashhad",
  "اصفهان": "Isfahan",
  "کرج": "Karaj",
  "شیراز": "Shiraz",
  "تبریز": "Tabriz",
  "قم": "Qom",
  "اهواز": "Ahvaz",
  "کرمانشاه": "Kermanshah",
  "رشت": "Rasht",
  "ارومیه": "Urmia",
  "زاهدان": "Zahedan",
  "کرمان": "Kerman",
  "همدان": "Hamadan",
  "یزد": "Yazd",
  "اردبیل": "Ardabil",
  "بندرعباس": "Bandar Abbas",
  "اراک": "Arak",
  "اسلام‌شهر": "Eslamshahr",
  "زنجان": "Zanjan",
  "سنندج": "Sanandaj",
  "قزوین": "Qazvin",
  "خرم‌آباد": "Khorramabad",
  "گرگان": "Gorgan",
  "ساری": "Sari",
  "کاشان": "Kashan",
  "دزفول": "Dezful",
  "بجنورد": "Bojnord",
  "بوشهر": "Bushehr",
  "سبزوار": "Sabzevar",
  "سیرجان": "Sirjan",
  "بابل": "Babol",
  "نجف‌آباد": "Najafabad",
  "آمل": "Amol",
  "شهرکرد": "Shahrekord",
  "یاسوج": "Yasuj",
  "بیرجند": "Birjand",
  "بندر انزلی": "Bandar Anzali",
  "خوی": "Khoy",
  "مرودشت": "Marvdasht",
  "بروجرد": "Borujerd",
  "قائم‌شهر": "Qaem Shahr",
  "نیشابور": "Neyshabur",
  "چابهار": "Chabahar",
  "مرند": "Marand",
  "شاهرود": "Shahrud",
  "ماهشهر": "Mahshahr",
  "میانه": "Miyaneh",
  "لار": "Lar",
  "رفسنجان": "Rafsanjan",
  "ایلام": "Ilam",
  "سمنان": "Semnan",
};

export function translateCityToEnglish(city: string): string {
  return cityToEnglish[city] ?? city;
}